// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/memo.dart';
import 'models/memo_annotation.dart';
import 'models/memo_space.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 3619786474663355254),
      name: 'Memo',
      lastPropertyId: const obx_int.IdUid(9, 448848594849084608),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7866426841083754578),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6523535534465401202),
            name: 'uuid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 1618732804066762906)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 5124437470914463588),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8821463411422235851),
            name: 'order',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5950445746345696126),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1251134166518726709),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4153634926445462919),
            name: 'deletedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3066971873439819002),
            name: 'version',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 448848594849084608),
            name: 'memoSpaceId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 2772776519555991962),
            relationTarget: 'MemoSpace')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'annotations', srcEntity: 'MemoAnnotation', srcField: 'memo')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 5723818514345253478),
      name: 'MemoSpace',
      lastPropertyId: const obx_int.IdUid(9, 311306172550151691),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2896873049959732990),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2708095340179127471),
            name: 'uuid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 7949768650164187234)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7583970680207265551),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5826931119400032624),
            name: 'legacyMemo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4358746528816006124),
            name: 'opened',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 2003961297809686401),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4172461422456314855),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 8279576259353283395),
            name: 'deletedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 311306172550151691),
            name: 'version',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'memos', srcEntity: 'Memo', srcField: 'memoSpace')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 8870753223861766809),
      name: 'MemoAnnotation',
      lastPropertyId: const obx_int.IdUid(9, 7136005943150079558),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3469065814669522110),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 9087770000339728175),
            name: 'uuid',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(4, 7928952671465296124)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7628407310853776417),
            name: 'startOffset',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5168676126797109900),
            name: 'endOffset',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 60503629625529690),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4420092240150998277),
            name: 'metadata',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2555225552797260535),
            name: 'createdAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6677816046767758137),
            name: 'updatedAt',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7136005943150079558),
            name: 'memoId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 1300961424400650137),
            relationTarget: 'Memo')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 8870753223861766809),
      lastIndexId: const obx_int.IdUid(5, 1300961424400650137),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Memo: obx_int.EntityDefinition<Memo>(
        model: _entities[0],
        toOneRelations: (Memo object) => [object.memoSpace],
        toManyRelations: (Memo object) => {
              obx_int.RelInfo<MemoAnnotation>.toOneBacklink(9, object.id,
                      (MemoAnnotation srcObject) => srcObject.memo):
                  object.annotations
            },
        getId: (Memo object) => object.id,
        setId: (Memo object, int id) {
          object.id = id;
        },
        objectToFB: (Memo object, fb.Builder fbb) {
          final uuidOffset = fbb.writeString(object.uuid);
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uuidOffset);
          fbb.addOffset(2, contentOffset);
          fbb.addInt64(3, object.order);
          fbb.addInt64(4, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(5, object.updatedAt.millisecondsSinceEpoch);
          fbb.addInt64(6, object.deletedAt?.millisecondsSinceEpoch);
          fbb.addInt64(7, object.version);
          fbb.addInt64(8, object.memoSpace.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final deletedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 16);
          final object = Memo()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uuid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..content = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..order =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0))
            ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0))
            ..deletedAt = deletedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(deletedAtValue)
            ..version =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.memoSpace.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.memoSpace.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Memo>(
              object.annotations,
              store,
              obx_int.RelInfo<MemoAnnotation>.toOneBacklink(
                  9, object.id, (MemoAnnotation srcObject) => srcObject.memo));
          return object;
        }),
    MemoSpace: obx_int.EntityDefinition<MemoSpace>(
        model: _entities[1],
        toOneRelations: (MemoSpace object) => [],
        toManyRelations: (MemoSpace object) => {
              obx_int.RelInfo<Memo>.toOneBacklink(
                      9, object.id, (Memo srcObject) => srcObject.memoSpace):
                  object.memos
            },
        getId: (MemoSpace object) => object.id,
        setId: (MemoSpace object, int id) {
          object.id = id;
        },
        objectToFB: (MemoSpace object, fb.Builder fbb) {
          final uuidOffset = fbb.writeString(object.uuid);
          final nameOffset = fbb.writeString(object.name);
          final legacyMemoOffset = object.legacyMemo == null
              ? null
              : fbb.writeString(object.legacyMemo!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uuidOffset);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, legacyMemoOffset);
          fbb.addBool(4, object.opened);
          fbb.addInt64(5, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(6, object.updatedAt.millisecondsSinceEpoch);
          fbb.addInt64(7, object.deletedAt?.millisecondsSinceEpoch);
          fbb.addInt64(8, object.version);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final deletedAtValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 18);
          final object = MemoSpace()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uuid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..name = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 8, '')
            ..legacyMemo = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 10)
            ..opened =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0))
            ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0))
            ..deletedAt = deletedAtValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(deletedAtValue)
            ..version =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          obx_int.InternalToManyAccess.setRelInfo<MemoSpace>(
              object.memos,
              store,
              obx_int.RelInfo<Memo>.toOneBacklink(
                  9, object.id, (Memo srcObject) => srcObject.memoSpace));
          return object;
        }),
    MemoAnnotation: obx_int.EntityDefinition<MemoAnnotation>(
        model: _entities[2],
        toOneRelations: (MemoAnnotation object) => [object.memo],
        toManyRelations: (MemoAnnotation object) => {},
        getId: (MemoAnnotation object) => object.id,
        setId: (MemoAnnotation object, int id) {
          object.id = id;
        },
        objectToFB: (MemoAnnotation object, fb.Builder fbb) {
          final uuidOffset = fbb.writeString(object.uuid);
          final typeOffset = fbb.writeString(object.type);
          final metadataOffset = object.metadata == null
              ? null
              : fbb.writeString(object.metadata!);
          fbb.startTable(10);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, uuidOffset);
          fbb.addInt64(2, object.startOffset);
          fbb.addInt64(3, object.endOffset);
          fbb.addOffset(4, typeOffset);
          fbb.addOffset(5, metadataOffset);
          fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
          fbb.addInt64(7, object.updatedAt.millisecondsSinceEpoch);
          fbb.addInt64(8, object.memo.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = MemoAnnotation()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..uuid = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..startOffset =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0)
            ..endOffset =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0)
            ..type = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 12, '')
            ..metadata = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..createdAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0))
            ..updatedAt = DateTime.fromMillisecondsSinceEpoch(
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0));
          object.memo.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.memo.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Memo] entity fields to define ObjectBox queries.
class Memo_ {
  /// See [Memo.id].
  static final id = obx.QueryIntegerProperty<Memo>(_entities[0].properties[0]);

  /// See [Memo.uuid].
  static final uuid = obx.QueryStringProperty<Memo>(_entities[0].properties[1]);

  /// See [Memo.content].
  static final content =
      obx.QueryStringProperty<Memo>(_entities[0].properties[2]);

  /// See [Memo.order].
  static final order =
      obx.QueryIntegerProperty<Memo>(_entities[0].properties[3]);

  /// See [Memo.createdAt].
  static final createdAt =
      obx.QueryDateProperty<Memo>(_entities[0].properties[4]);

  /// See [Memo.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<Memo>(_entities[0].properties[5]);

  /// See [Memo.deletedAt].
  static final deletedAt =
      obx.QueryDateProperty<Memo>(_entities[0].properties[6]);

  /// See [Memo.version].
  static final version =
      obx.QueryIntegerProperty<Memo>(_entities[0].properties[7]);

  /// See [Memo.memoSpace].
  static final memoSpace =
      obx.QueryRelationToOne<Memo, MemoSpace>(_entities[0].properties[8]);

  /// see [Memo.annotations]
  static final annotations =
      obx.QueryBacklinkToMany<MemoAnnotation, Memo>(MemoAnnotation_.memo);
}

/// [MemoSpace] entity fields to define ObjectBox queries.
class MemoSpace_ {
  /// See [MemoSpace.id].
  static final id =
      obx.QueryIntegerProperty<MemoSpace>(_entities[1].properties[0]);

  /// See [MemoSpace.uuid].
  static final uuid =
      obx.QueryStringProperty<MemoSpace>(_entities[1].properties[1]);

  /// See [MemoSpace.name].
  static final name =
      obx.QueryStringProperty<MemoSpace>(_entities[1].properties[2]);

  /// See [MemoSpace.legacyMemo].
  static final legacyMemo =
      obx.QueryStringProperty<MemoSpace>(_entities[1].properties[3]);

  /// See [MemoSpace.opened].
  static final opened =
      obx.QueryBooleanProperty<MemoSpace>(_entities[1].properties[4]);

  /// See [MemoSpace.createdAt].
  static final createdAt =
      obx.QueryDateProperty<MemoSpace>(_entities[1].properties[5]);

  /// See [MemoSpace.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<MemoSpace>(_entities[1].properties[6]);

  /// See [MemoSpace.deletedAt].
  static final deletedAt =
      obx.QueryDateProperty<MemoSpace>(_entities[1].properties[7]);

  /// See [MemoSpace.version].
  static final version =
      obx.QueryIntegerProperty<MemoSpace>(_entities[1].properties[8]);

  /// see [MemoSpace.memos]
  static final memos =
      obx.QueryBacklinkToMany<Memo, MemoSpace>(Memo_.memoSpace);
}

/// [MemoAnnotation] entity fields to define ObjectBox queries.
class MemoAnnotation_ {
  /// See [MemoAnnotation.id].
  static final id =
      obx.QueryIntegerProperty<MemoAnnotation>(_entities[2].properties[0]);

  /// See [MemoAnnotation.uuid].
  static final uuid =
      obx.QueryStringProperty<MemoAnnotation>(_entities[2].properties[1]);

  /// See [MemoAnnotation.startOffset].
  static final startOffset =
      obx.QueryIntegerProperty<MemoAnnotation>(_entities[2].properties[2]);

  /// See [MemoAnnotation.endOffset].
  static final endOffset =
      obx.QueryIntegerProperty<MemoAnnotation>(_entities[2].properties[3]);

  /// See [MemoAnnotation.type].
  static final type =
      obx.QueryStringProperty<MemoAnnotation>(_entities[2].properties[4]);

  /// See [MemoAnnotation.metadata].
  static final metadata =
      obx.QueryStringProperty<MemoAnnotation>(_entities[2].properties[5]);

  /// See [MemoAnnotation.createdAt].
  static final createdAt =
      obx.QueryDateProperty<MemoAnnotation>(_entities[2].properties[6]);

  /// See [MemoAnnotation.updatedAt].
  static final updatedAt =
      obx.QueryDateProperty<MemoAnnotation>(_entities[2].properties[7]);

  /// See [MemoAnnotation.memo].
  static final memo =
      obx.QueryRelationToOne<MemoAnnotation, Memo>(_entities[2].properties[8]);
}
